# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f59f63170ce7d5fef7b97f105b92f735feb351b0a5685747626667cb7e11bfb548f2eda156e7d918c4e664daf7bd9abb2d81ebbc5ab03fe8c639570efb07cb4

test:
  secret_key_base: 22dfc06411e28280997fc92ea02c2a243ecb4c9705b28fc89b8d876da32767f23d31c3eb43618542209c53f1ac2fa1bba0ee802fe5c789b3b4319f099065cf45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
